config/routes.rb
Rails.application.routes.draw do
  resources :survivors
  # get 'home/index'

  root 'home#index'

  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/survivor.rb
class Survivor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/survivors_controller.rb
class SurvivorsController < ApplicationController
  before_action :set_survivor, only: %i[ show edit update destroy ]

  # GET /survivors or /survivors.json
  def index
    @survivors = Survivor.all
  end

  # GET /survivors/1 or /survivors/1.json
  def show
  end

  # GET /survivors/new
  def new
    @survivor = Survivor.new
  end

  # GET /survivors/1/edit
  def edit
  end

  # POST /survivors or /survivors.json
  def create
    @survivor = Survivor.new(survivor_params)

    respond_to do |format|
      if @survivor.save
        format.html { redirect_to survivor_url(@survivor), notice: "Survivor was successfully created." }
        format.json { render :show, status: :created, location: @survivor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survivors/1 or /survivors/1.json
  def update
    respond_to do |format|
      if @survivor.update(survivor_params)
        format.html { redirect_to survivor_url(@survivor), notice: "Survivor was successfully updated." }
        format.json { render :show, status: :ok, location: @survivor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survivors/1 or /survivors/1.json
  def destroy
    @survivor.destroy

    respond_to do |format|
      format.html { redirect_to survivors_url, notice: "Survivor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survivor
      @survivor = Survivor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survivor_params
      params.require(:survivor).permit(:age, :age, :gender, :last_location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/survivors_helper.rb
module SurvivorsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a>
  <%= link_to 'X-Sunit', root_path, class:'navbar-brand' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a>
      <%= link_to 'Survivors', survivors_path, class:'nav-link sr-only' %>
      </a>
      <a>
      <%= link_to 'Add survivor', new_survivor_path, class:'nav-link' %>
      </a>
      <a>
      <%= link_to 'About', home_about_path, class:'nav-link' %>
      </a>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>X-SUNIT: Survivor's unit</h1>
<p>The Earth is facing an allien apocalypse: people are getting abducted by alliens and being replaced with identical evil clones!</p>
<p>Our mission is to help what is left of the human race by keeping track of the survivors in our planet. You can help by reporting as many survivors as you know (including yourself) and reporting abductions.</p>
<p>This way, we can join forces and get the planet back on track!</p>

app/views/home/index.html.erb
<h1>X-SUNIT</h1>
<h3>Human survivors official tracking</h3>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.rtl.min.css" integrity="sha384-dc2NSrAXbAkjrdm9IYrX10fQq9SDG6Vjz7nQVKdKcJl3pC+k37e7qJR5MVSCS+wR" crossorigin="anonymous">

    <title>XSunit</title>
  </head>
  <body>

  <%= render 'home/header' %>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    -->
  </body>
</html>


<!DOCTYPE html>
<html>
  <head>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/survivors/_form.html.erb
<%= form_with(model: survivor) do |form| %>
  <% if survivor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survivor.errors.count, "error") %> prohibited this survivor from being saved:</h2>

      <ul>
        <% survivor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :last_location, style: "display: block" %>
    <%= form.text_field :last_location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/survivors/_survivor.html.erb
<div id="<%= dom_id survivor %>">
  <p>
    <strong>Name:</strong>
    <%= survivor.age %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= survivor.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= survivor.gender %>
  </p>

  <p>
    <strong>Last location:</strong>
    <%= survivor.last_location %>
  </p>

</div>

app/views/survivors/edit.html.erb
<h1>Editing survivor</h1>

<%= render "form", survivor: @survivor %>

<br>

<div>
  <%= link_to "Show this survivor", @survivor %> |
  <%= link_to "Back to survivors", survivors_path %>
</div>

app/views/survivors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Survivors</h1>

<div id="survivors">
  <% @survivors.each do |survivor| %>
    <%= render survivor %>
    <p>
      <%= link_to "Show this survivor", survivor %>
    </p>
  <% end %>
</div>

<%= link_to "New survivor", new_survivor_path %>

app/views/survivors/new.html.erb
<h1>New survivor</h1>

<%= render "form", survivor: @survivor %>

<br>

<div>
  <%= link_to "Back to survivors", survivors_path %>
</div>

app/views/survivors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survivor %>

<div>
  <%= link_to "Edit this survivor", edit_survivor_path(@survivor) %> |
  <%= link_to "Back to survivors", survivors_path %>

  <%= button_to "Destroy this survivor", @survivor, method: :delete %>
</div>